public enum Faculty {
    INTERNATIONAL_ECONOMICS,
    INTERNATIONAL_TECHNOLOGY_ENGINEERING,
    ENERGY_PETROLEUM_ENGINEERING,
    APPLIED_MATHEMATICS,
    BUSINESS,
    GEOLOGY,
    MARITIME_ACADEMY,
    MATERIAL_SCIENCE_GREEN_TECHNOLOGY,
    CHEMICAL_ENGINEERING
}
